set -g default-terminal "tmux-256color"
set-option -sa terminal-overrides ",xterm*:Tc"
set-option -ga terminal-overrides ",xterm-256color:Tc"
set-option -sa terminal-overrides ",*kitty*:Tc"

# Behavior & Usability
set -g mouse on                       # Enable mouse support
set -g base-index 1                   # Start windows at 1
setw -g pane-base-index 1             # Start panes at 1
set -g renumber-windows on            # Renumber after close
set -g history-limit 10000            # Bigger scrollback
set -s escape-time 0                  # Faster escape sequences

# Prefix & Reload
unbind C-b
set -g prefix C-a
bind C-a send-prefix
bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"

# Split panes using | and -
bind v split-window -h -c "#{pane_current_path}"
bind h split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Alt+h/j/k/l to switch panes without prefix
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# Status Bar
set -g status-position top
set -g status-interval 5              # refresh every 5s

# Left side: session + window
set -g status-left "#[fg=green]#S #[fg=blue]| #[fg=yellow]#I:#W "

#
# set -g @tmux-gruvbox-right-status-x '#(~/.tmux/plugins/tmux-battery/scripts/battery_percentage.sh) | %Y-%m-%d'
# Updated status right with battery and network
# set -g status-right '#[fg=green]#{online_status} #[fg=yellow]#{battery_icon} #{battery_percentage} #[fg=blue]%Y-%m-%d #[fg=white]%H:%M'
set -g status-right '#[fg=yellow]#{battery_icon}#{battery_percentage} #[fg=cyan]%H:%M'

# ==============================
# Plugins (TPM required)
# ==============================
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'egel/tmux-gruvbox'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @tmux-gruvbox 'dark'
set -g @copycat_mouse 'on'
set -g @plugin 'tmux-plugins/tmux-battery'

# Resurrect/Continuum settings
set -g @resurrect-capture-pane-contents 'off'
set -g @continuum-restore 'off'

# Set default shell to Zsh
set-option -g default-shell /run/current-system/sw/bin/zsh
set-option -g default-command /run/current-system/sw/bin/zsh

# Initialize TPM
run '~/.tmux/plugins/tpm/tpm'
